### ISSUE TITLE
Failed to build

### ISSUE THREAD

**Issue by KieronWiltshire** [tfeng/collection#4]
I'm using VB 2015 community edition and I've installed the Visual C++ stuff

```
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install',
1 verbose cli   '--save',
1 verbose cli   'collection' ]
2 info using npm@2.14.4
3 info using node@v4.1.1
4 verbose install initial load of C:\Users\C1542295\Projects\ezpermissions\package.json
5 verbose installManyTop reading scoped package data from C:\Users\C1542295\Projects\ezpermissions\node_modules\uuid\package.json
6 info package.json uuid@2.0.1 No license field.
7 verbose readDependencies loading dependencies from C:\Users\C1542295\Projects\ezpermissions\package.json
8 silly cache add args [ 'collection', null ]
9 verbose cache add spec collection
10 silly cache add parsed spec Result {
10 silly cache add   raw: 'collection',
10 silly cache add   scope: null,
10 silly cache add   name: 'collection',
10 silly cache add   rawSpec: '',
10 silly cache add   spec: '*',
10 silly cache add   type: 'range' }
11 silly addNamed collection@*
12 verbose addNamed "*" is a valid semver range for collection
13 silly addNameRange { name: 'collection', range: '*', hasData: false }
14 silly mapToRegistry name collection
15 silly mapToRegistry using default registry
16 silly mapToRegistry registry https://registry.npmjs.org/
17 silly mapToRegistry uri https://registry.npmjs.org/collection
18 verbose addNameRange registry:https://registry.npmjs.org/collection not in flight; fetching
19 verbose request uri https://registry.npmjs.org/collection
20 verbose request no auth needed
21 info attempt registry request try #1 at 11:15:02 PM
22 verbose request using bearer token for auth
23 verbose request id 35d93d367858efbd
24 verbose etag "2JM0T8F8H774J9RHO8XNFBFOO"
25 http request GET https://registry.npmjs.org/collection
26 http 304 https://registry.npmjs.org/collection
27 silly get cb [ 304,
27 silly get   { 'cache-control': 'max-age=60',
27 silly get     'accept-ranges': 'bytes',
27 silly get     date: 'Wed, 18 Nov 2015 23:14:59 GMT',
27 silly get     via: '1.1 varnish',
27 silly get     connection: 'keep-alive',
27 silly get     'x-served-by': 'cache-ams4128-AMS',
27 silly get     'x-cache': 'MISS',
27 silly get     'x-cache-hits': '0',
27 silly get     'x-timer': 'S1447888499.562124,VS0,VE407' } ]
28 verbose etag https://registry.npmjs.org/collection from cache
29 verbose get saving collection to C:\Users\C1542295\AppData\Roaming\npm-cache\registry.npmjs.org\collection\.cache.json
30 silly addNameRange number 2 { name: 'collection', range: '*', hasData: true }
31 silly addNameRange versions [ 'collection',
31 silly addNameRange   [ '0.1.0', '0.1.1', '0.1.2', '0.1.3', '0.1.4', '0.1.5', '0.1.6' ] ]
32 silly addNamed collection@0.1.6
33 verbose addNamed "0.1.6" is a plain semver version for collection
34 silly cache afterAdd collection@0.1.6
35 verbose afterAdd C:\Users\C1542295\AppData\Roaming\npm-cache\collection\0.1.6\package\package.json not in flight; writing
36 verbose afterAdd C:\Users\C1542295\AppData\Roaming\npm-cache\collection\0.1.6\package\package.json written
37 silly install resolved [ { name: 'collection',
37 silly install resolved     id: 'collection',
37 silly install resolved     version: '0.1.6',
37 silly install resolved     description: 'Node.js cross-platform native collection library',
37 silly install resolved     keywords: [ 'collection', 'native', 'util', 'vector', 'set', 'map' ],
37 silly install resolved     author: { name: 'Thomas Feng', email: 'tfeng@berkeley.edu' },
37 silly install resolved     homepage: 'http://tfeng.github.io/collection',
37 silly install resolved     repository:
37 silly install resolved      { type: 'git',
37 silly install resolved        url: 'git+https://github.com/tfeng/collection.git',
37 silly install resolved        web: 'https://github.com/tfeng/collection' },
37 silly install resolved     bugs: { url: 'https://github.com/tfeng/collection/issues' },
37 silly install resolved     main: './lib/collection.js',
37 silly install resolved     licenses: [ [Object] ],
37 silly install resolved     dependencies: { bindings: 'latest' },
37 silly install resolved     scripts: { install: 'node-gyp rebuild' },
37 silly install resolved     gypfile: true,
37 silly install resolved     gitHead: '0e7545cfd5f5b02d3fa5dba8e6b95d0a1f6724f9',
37 silly install resolved     _id: 'collection@0.1.6',
37 silly install resolved     _shasum: '971cf4f80f598f5f170a7067d1ac2083099580fd',
37 silly install resolved     _from: 'collection@*',
37 silly install resolved     _npmVersion: '1.4.28',
37 silly install resolved     _npmUser: { name: 'tfeng', email: 'tfeng@berkeley.edu' },
37 silly install resolved     maintainers: [ [Object] ],
37 silly install resolved     dist:
37 silly install resolved      { shasum: '971cf4f80f598f5f170a7067d1ac2083099580fd',
37 silly install resolved        tarball: 'http://registry.npmjs.org/collection/-/collection-0.1.6.tgz' },
37 silly install resolved     directories: {},
37 silly install resolved     _resolved: 'https://registry.npmjs.org/collection/-/collection-0.1.6.tgz',
37 silly install resolved     readme: 'ERROR: No README data found!' } ]
38 info install collection@0.1.6 into C:\Users\C1542295\Projects\ezpermissions
39 info installOne collection@0.1.6
40 verbose installOne of collection to C:\Users\C1542295\Projects\ezpermissions not in flight; installing
41 verbose lock using C:\Users\C1542295\AppData\Roaming\npm-cache\_locks\collection-905794723a18b44e.lock for C:\Users\C1542295\Projects\ezpermissions\node_modules\collection
42 silly install write writing collection 0.1.6 to C:\Users\C1542295\Projects\ezpermissions\node_modules\collection
43 verbose unbuild node_modules\collection
44 silly gentlyRm C:\Users\C1542295\Projects\ezpermissions\node_modules\collection is being purged from base C:\Users\C1542295\Projects\ezpermissions
45 verbose gentlyRm don't care about contents; nuking C:\Users\C1542295\Projects\ezpermissions\node_modules\collection
46 verbose tar unpack C:\Users\C1542295\AppData\Roaming\npm-cache\collection\0.1.6\package.tgz
47 verbose tar unpacking to C:\Users\C1542295\Projects\ezpermissions\node_modules\collection
48 silly gentlyRm C:\Users\C1542295\Projects\ezpermissions\node_modules\collection is being purged
49 verbose gentlyRm don't care about contents; nuking C:\Users\C1542295\Projects\ezpermissions\node_modules\collection
50 silly gunzTarPerm modes [ '777', '666' ]
51 silly gunzTarPerm extractEntry package.json
52 silly gunzTarPerm modified mode [ 'package.json', 420, 438 ]
53 silly gunzTarPerm extractEntry README.md
54 silly gunzTarPerm modified mode [ 'README.md', 420, 438 ]
55 silly gunzTarPerm extractEntry lib/collection.js
56 silly gunzTarPerm modified mode [ 'lib/collection.js', 420, 438 ]
57 silly gunzTarPerm extractEntry build/Makefile
58 silly gunzTarPerm modified mode [ 'build/Makefile', 420, 438 ]
59 silly gunzTarPerm extractEntry build/NativeTypes.target.mk
60 silly gunzTarPerm modified mode [ 'build/NativeTypes.target.mk', 420, 438 ]
61 silly gunzTarPerm extractEntry build/Release/.deps/Release/NativeTypes.node.d
62 silly gunzTarPerm modified mode [ 'build/Release/.deps/Release/NativeTypes.node.d', 420, 438 ]
63 silly gunzTarPerm extractEntry build/Release/.deps/Release/obj.target/NativeTypes/src/Map.o.d
64 silly gunzTarPerm modified mode [ 'build/Release/.deps/Release/obj.target/NativeTypes/src/Map.o.d',
64 silly gunzTarPerm   420,
64 silly gunzTarPerm   438 ]
65 silly gunzTarPerm extractEntry build/Release/.deps/Release/obj.target/NativeTypes/src/NativeTypes.o.d
66 silly gunzTarPerm modified mode [ 'build/Release/.deps/Release/obj.target/NativeTypes/src/NativeTypes.o.d',
66 silly gunzTarPerm   420,
66 silly gunzTarPerm   438 ]
67 silly gunzTarPerm extractEntry build/Release/.deps/Release/obj.target/NativeTypes/src/Set.o.d
68 silly gunzTarPerm modified mode [ 'build/Release/.deps/Release/obj.target/NativeTypes/src/Set.o.d',
68 silly gunzTarPerm   420,
68 silly gunzTarPerm   438 ]
69 silly gunzTarPerm extractEntry build/Release/.deps/Release/obj.target/NativeTypes/src/Vector.o.d
70 silly gunzTarPerm modified mode [ 'build/Release/.deps/Release/obj.target/NativeTypes/src/Vector.o.d',
70 silly gunzTarPerm   420,
70 silly gunzTarPerm   438 ]
71 silly gunzTarPerm extractEntry build/Release/.deps/Release/obj.target/NativeTypes/src/common.o.d
72 silly gunzTarPerm modified mode [ 'build/Release/.deps/Release/obj.target/NativeTypes/src/common.o.d',
72 silly gunzTarPerm   420,
72 silly gunzTarPerm   438 ]
73 silly gunzTarPerm extractEntry build/Release/NativeTypes.node
74 silly gunzTarPerm modified mode [ 'build/Release/NativeTypes.node', 493, 511 ]
75 silly gunzTarPerm extractEntry build/Release/linker.lock
76 silly gunzTarPerm modified mode [ 'build/Release/linker.lock', 420, 438 ]
77 silly gunzTarPerm extractEntry build/Release/obj.target/NativeTypes/src/Map.o
78 silly gunzTarPerm modified mode [ 'build/Release/obj.target/NativeTypes/src/Map.o', 420, 438 ]
79 silly gunzTarPerm extractEntry build/Release/obj.target/NativeTypes/src/NativeTypes.o
80 silly gunzTarPerm modified mode [ 'build/Release/obj.target/NativeTypes/src/NativeTypes.o',
80 silly gunzTarPerm   420,
80 silly gunzTarPerm   438 ]
81 silly gunzTarPerm extractEntry build/Release/obj.target/NativeTypes/src/Set.o
82 silly gunzTarPerm modified mode [ 'build/Release/obj.target/NativeTypes/src/Set.o', 420, 438 ]
83 silly gunzTarPerm extractEntry build/Release/obj.target/NativeTypes/src/Vector.o
84 silly gunzTarPerm modified mode [ 'build/Release/obj.target/NativeTypes/src/Vector.o', 420, 438 ]
85 silly gunzTarPerm extractEntry build/Release/obj.target/NativeTypes/src/common.o
86 silly gunzTarPerm modified mode [ 'build/Release/obj.target/NativeTypes/src/common.o', 420, 438 ]
87 silly gunzTarPerm extractEntry build/binding.Makefile
88 silly gunzTarPerm modified mode [ 'build/binding.Makefile', 420, 438 ]
89 silly gunzTarPerm extractEntry build/config.gypi
90 silly gunzTarPerm modified mode [ 'build/config.gypi', 420, 438 ]
91 silly gunzTarPerm extractEntry build/gyp-mac-tool
92 silly gunzTarPerm modified mode [ 'build/gyp-mac-tool', 493, 511 ]
93 silly gunzTarPerm extractEntry src/Map.cc
94 silly gunzTarPerm modified mode [ 'src/Map.cc', 420, 438 ]
95 silly gunzTarPerm extractEntry src/Map.h
96 silly gunzTarPerm modified mode [ 'src/Map.h', 420, 438 ]
97 silly gunzTarPerm extractEntry src/NativeTypes.cc
98 silly gunzTarPerm modified mode [ 'src/NativeTypes.cc', 420, 438 ]
99 silly gunzTarPerm extractEntry src/Set.cc
100 silly gunzTarPerm modified mode [ 'src/Set.cc', 420, 438 ]
101 silly gunzTarPerm extractEntry src/Set.h
102 silly gunzTarPerm modified mode [ 'src/Set.h', 420, 438 ]
103 silly gunzTarPerm extractEntry src/Vector.cc
104 silly gunzTarPerm modified mode [ 'src/Vector.cc', 420, 438 ]
105 silly gunzTarPerm extractEntry src/Vector.h
106 silly gunzTarPerm modified mode [ 'src/Vector.h', 420, 438 ]
107 silly gunzTarPerm extractEntry src/common.cc
108 silly gunzTarPerm modified mode [ 'src/common.cc', 420, 438 ]
109 silly gunzTarPerm extractEntry src/common.h
110 silly gunzTarPerm modified mode [ 'src/common.h', 420, 438 ]
111 silly gunzTarPerm extractEntry binding.gyp
112 silly gunzTarPerm modified mode [ 'binding.gyp', 420, 438 ]
113 silly gunzTarPerm extractEntry test/test-map.js
114 silly gunzTarPerm modified mode [ 'test/test-map.js', 420, 438 ]
115 silly gunzTarPerm extractEntry test/test-set.js
116 silly gunzTarPerm modified mode [ 'test/test-set.js', 420, 438 ]
117 silly gunzTarPerm extractEntry test/test-vector.js
118 silly gunzTarPerm modified mode [ 'test/test-vector.js', 420, 438 ]
119 verbose write writing to C:\Users\C1542295\Projects\ezpermissions\node_modules\collection\package.json
120 info preinstall collection@0.1.6
121 verbose readDependencies loading dependencies from C:\Users\C1542295\Projects\ezpermissions\node_modules\collection\package.json
122 silly prepareForInstallMany adding bindings@latest from collection dependencies
123 verbose readDependencies loading dependencies from C:\Users\C1542295\Projects\ezpermissions\node_modules\collection\package.json
124 silly cache add args [ 'bindings@latest', null ]
125 verbose cache add spec bindings@latest
126 silly cache add parsed spec Result {
126 silly cache add   raw: 'bindings@latest',
126 silly cache add   scope: null,
126 silly cache add   name: 'bindings',
126 silly cache add   rawSpec: 'latest',
126 silly cache add   spec: 'latest',
126 silly cache add   type: 'tag' }
127 silly addNamed bindings@latest
128 verbose addNamed "latest" is being treated as a dist-tag for bindings
129 info addNameTag [ 'bindings', 'latest' ]
130 silly mapToRegistry name bindings
131 silly mapToRegistry using default registry
132 silly mapToRegistry registry https://registry.npmjs.org/
133 silly mapToRegistry uri https://registry.npmjs.org/bindings
134 verbose addNameTag registry:https://registry.npmjs.org/bindings not in flight; fetching
135 verbose request uri https://registry.npmjs.org/bindings
136 verbose request no auth needed
137 info attempt registry request try #1 at 11:15:03 PM
138 verbose request using bearer token for auth
139 verbose etag "2RXG5K4RRQWEOOFOAOOKVPOZR"
140 http request GET https://registry.npmjs.org/bindings
141 http 304 https://registry.npmjs.org/bindings
142 silly get cb [ 304,
142 silly get   { 'cache-control': 'max-age=60',
142 silly get     'accept-ranges': 'bytes',
142 silly get     date: 'Wed, 18 Nov 2015 23:15:00 GMT',
142 silly get     via: '1.1 varnish',
142 silly get     connection: 'keep-alive',
142 silly get     'x-served-by': 'cache-ams4144-AMS',
142 silly get     'x-cache': 'MISS',
142 silly get     'x-cache-hits': '0',
142 silly get     'x-timer': 'S1447888500.590257,VS0,VE398' } ]
143 verbose etag https://registry.npmjs.org/bindings from cache
144 verbose get saving bindings to C:\Users\C1542295\AppData\Roaming\npm-cache\registry.npmjs.org\bindings\.cache.json
145 silly addNameTag next cb for bindings with tag latest
146 silly addNamed bindings@1.2.1
147 verbose addNamed "1.2.1" is a plain semver version for bindings
148 silly cache afterAdd bindings@1.2.1
149 verbose afterAdd C:\Users\C1542295\AppData\Roaming\npm-cache\bindings\1.2.1\package\package.json not in flight; writing
150 verbose afterAdd C:\Users\C1542295\AppData\Roaming\npm-cache\bindings\1.2.1\package\package.json written
151 silly install resolved [ { name: 'bindings',
151 silly install resolved     description: 'Helper module for loading your native module\'s .node file',
151 silly install resolved     keywords: [ 'native', 'addon', 'bindings', 'gyp', 'waf', 'c', 'c++' ],
151 silly install resolved     version: '1.2.1',
151 silly install resolved     author:
151 silly install resolved      { name: 'Nathan Rajlich',
151 silly install resolved        email: 'nathan@tootallnate.net',
151 silly install resolved        url: 'http://tootallnate.net' },
151 silly install resolved     repository:
151 silly install resolved      { type: 'git',
151 silly install resolved        url: 'git://github.com/TooTallNate/node-bindings.git' },
151 silly install resolved     main: './bindings.js',
151 silly install resolved     bugs: { url: 'https://github.com/TooTallNate/node-bindings/issues' },
151 silly install resolved     homepage: 'https://github.com/TooTallNate/node-bindings',
151 silly install resolved     license: 'MIT',
151 silly install resolved     gitHead: 'e404152ee27f8478ccbc7122ee051246e8e5ec02',
151 silly install resolved     _id: 'bindings@1.2.1',
151 silly install resolved     scripts: {},
151 silly install resolved     _shasum: '14ad6113812d2d37d72e67b4cacb4bb726505f11',
151 silly install resolved     _from: 'bindings@latest',
151 silly install resolved     _npmVersion: '1.4.14',
151 silly install resolved     _npmUser: { name: 'tootallnate', email: 'nathan@tootallnate.net' },
151 silly install resolved     maintainers: [ [Object], [Object] ],
151 silly install resolved     dist:
151 silly install resolved      { shasum: '14ad6113812d2d37d72e67b4cacb4bb726505f11',
151 silly install resolved        tarball: 'http://registry.npmjs.org/bindings/-/bindings-1.2.1.tgz' },
151 silly install resolved     directories: {},
151 silly install resolved     _resolved: 'https://registry.npmjs.org/bindings/-/bindings-1.2.1.tgz',
151 silly install resolved     readme: 'ERROR: No README data found!' } ]
152 info install bindings@1.2.1 into C:\Users\C1542295\Projects\ezpermissions\node_modules\collection
153 info installOne bindings@1.2.1
154 verbose installOne of bindings to C:\Users\C1542295\Projects\ezpermissions\node_modules\collection not in flight; installing
155 verbose lock using C:\Users\C1542295\AppData\Roaming\npm-cache\_locks\bindings-e00f9e1673359046.lock for C:\Users\C1542295\Projects\ezpermissions\node_modules\collection\node_modules\bindings
156 silly install write writing bindings 1.2.1 to C:\Users\C1542295\Projects\ezpermissions\node_modules\collection\node_modules\bindings
157 verbose unbuild node_modules\collection\node_modules\bindings
158 silly gentlyRm C:\Users\C1542295\Projects\ezpermissions\node_modules\collection\node_modules\bindings is being purged from base C:\Users\C1542295\Projects\ezpermissions
159 verbose gentlyRm don't care about contents; nuking C:\Users\C1542295\Projects\ezpermissions\node_modules\collection\node_modules\bindings
160 verbose tar unpack C:\Users\C1542295\AppData\Roaming\npm-cache\bindings\1.2.1\package.tgz
161 verbose tar unpacking to C:\Users\C1542295\Projects\ezpermissions\node_modules\collection\node_modules\bindings
162 silly gentlyRm C:\Users\C1542295\Projects\ezpermissions\node_modules\collection\node_modules\bindings is being purged
163 verbose gentlyRm don't care about contents; nuking C:\Users\C1542295\Projects\ezpermissions\node_modules\collection\node_modules\bindings
164 silly gunzTarPerm modes [ '777', '666' ]
165 silly gunzTarPerm extractEntry package.json
166 silly gunzTarPerm modified mode [ 'package.json', 420, 438 ]
167 silly gunzTarPerm extractEntry README.md
168 silly gunzTarPerm modified mode [ 'README.md', 420, 438 ]
169 silly gunzTarPerm extractEntry bindings.js
170 silly gunzTarPerm modified mode [ 'bindings.js', 420, 438 ]
171 verbose write writing to C:\Users\C1542295\Projects\ezpermissions\node_modules\collection\node_modules\bindings\package.json
172 info preinstall bindings@1.2.1
173 verbose readDependencies loading dependencies from C:\Users\C1542295\Projects\ezpermissions\node_modules\collection\node_modules\bindings\package.json
174 verbose readDependencies loading dependencies from C:\Users\C1542295\Projects\ezpermissions\node_modules\collection\node_modules\bindings\package.json
175 silly install resolved []
176 verbose about to build C:\Users\C1542295\Projects\ezpermissions\node_modules\collection\node_modules\bindings
177 info build C:\Users\C1542295\Projects\ezpermissions\node_modules\collection\node_modules\bindings
178 info linkStuff bindings@1.2.1
179 silly linkStuff bindings@1.2.1 has C:\Users\C1542295\Projects\ezpermissions\node_modules\collection\node_modules as its parent node_modules
180 verbose linkBins bindings@1.2.1
181 verbose linkMans bindings@1.2.1
182 verbose rebuildBundles bindings@1.2.1
183 info install bindings@1.2.1
184 info postinstall bindings@1.2.1
185 verbose unlock done using C:\Users\C1542295\AppData\Roaming\npm-cache\_locks\bindings-e00f9e1673359046.lock for C:\Users\C1542295\Projects\ezpermissions\node_modules\collection\node_modules\bindings
186 verbose about to build C:\Users\C1542295\Projects\ezpermissions\node_modules\collection
187 info build C:\Users\C1542295\Projects\ezpermissions\node_modules\collection
188 info linkStuff collection@0.1.6
189 silly linkStuff collection@0.1.6 has C:\Users\C1542295\Projects\ezpermissions\node_modules as its parent node_modules
190 verbose linkBins collection@0.1.6
191 verbose linkMans collection@0.1.6
192 verbose rebuildBundles collection@0.1.6
193 verbose rebuildBundles [ 'bindings' ]
194 info install collection@0.1.6
195 verbose unsafe-perm in lifecycle true
196 info collection@0.1.6 Failed to exec install script
197 verbose unlock done using C:\Users\C1542295\AppData\Roaming\npm-cache\_locks\collection-905794723a18b44e.lock for C:\Users\C1542295\Projects\ezpermissions\node_modules\collection
198 verbose stack Error: collection@0.1.6 install: `node-gyp rebuild`
198 verbose stack Exit status 1
198 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\lifecycle.js:214:16)
198 verbose stack     at emitTwo (events.js:87:13)
198 verbose stack     at EventEmitter.emit (events.js:172:7)
198 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\spawn.js:24:14)
198 verbose stack     at emitTwo (events.js:87:13)
198 verbose stack     at ChildProcess.emit (events.js:172:7)
198 verbose stack     at maybeClose (internal/child_process.js:817:16)
198 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
199 verbose pkgid collection@0.1.6
200 verbose cwd C:\Users\C1542295\Projects\ezpermissions
201 error Windows_NT 6.1.7601
202 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "--save" "collection"
203 error node v4.1.1
204 error npm  v2.14.4
205 error code ELIFECYCLE
206 error collection@0.1.6 install: `node-gyp rebuild`
206 error Exit status 1
207 error Failed at the collection@0.1.6 install script 'node-gyp rebuild'.
207 error This is most likely a problem with the collection package,
207 error not with npm itself.
207 error Tell the author that this fails on your system:
207 error     node-gyp rebuild
207 error You can get their info via:
207 error     npm owner ls collection
207 error There is likely additional logging output above.
208 verbose exit [ 1, true ]
209 verbose unbuild node_modules\collection
210 info preuninstall collection@0.1.6
211 info uninstall collection@0.1.6
212 verbose unbuild rmStuff collection@0.1.6 from C:\Users\C1542295\Projects\ezpermissions\node_modules
213 info postuninstall collection@0.1.6
214 silly gentlyRm C:\Users\C1542295\Projects\ezpermissions\node_modules\collection is being purged from base C:\Users\C1542295\Projects\ezpermissions
215 verbose gentlyRm don't care about contents; nuking C:\Users\C1542295\Projects\ezpermissions\node_modules\collection
216 silly vacuum-fs purging C:\Users\C1542295\Projects\ezpermissions\node_modules\collection
217 silly vacuum-fs quitting because other entries in C:\Users\C1542295\Projects\ezpermissions\node_modules
```

**Comment by tfeng** [comment]
The build has not tested with node 4. Could you try building it with node v0.12.7 here (https://nodejs.org/en/download/releases/)? Let me know if it works or not.

I don't have a system to test this right now, but I will test in a few days/weeks.
